/**
 * Codegen: reads providers/{region}/ → writes src/data-{region}.ts
 *
 * Usage:
 *   bun scripts/generate.ts         # default: --us
 *   bun scripts/generate.ts --cn
 *   bun scripts/generate.ts --us
 */
import * as fs from "node:fs";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");

const region = (process.argv.includes("--cn") ? "cn" : "us") as "cn" | "us";

const HEADER = [
  "// This file is auto-generated by scripts/generate.ts",
  "// Do not edit manually",
  "",
];

const ALL_MODELS_SNIPPET = [
  "export const allModels: Model[] = providers.flatMap((p) =>",
  "  p.models.map((m) => ({ ...m, provider: p.id }))",
  ");",
  "",
];

function generateRegion(region: "cn" | "us") {
  const DATA_OUTPUT = path.join(ROOT, "src", `data-${region}.ts`);
  const providersDir = path.join(ROOT, "providers", region);
  if (!fs.existsSync(providersDir)) {
    console.warn(`Directory not found: providers/${region}/ — skipping`);
    process.exit(0);
  }

  const providerDirs = fs
    .readdirSync(providersDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const providers: Array<{
    id: string;
    provider: Record<string, unknown>;
    models: Record<string, unknown>[];
  }> = [];

  for (const dir of providerDirs) {
    const providerPath = path.join(providersDir, dir, "_provider.json");
    if (!fs.existsSync(providerPath)) continue;

    const provider = JSON.parse(fs.readFileSync(providerPath, "utf-8"));

    const iconPath = path.join(providersDir, dir, "icon.svg");
    if (fs.existsSync(iconPath)) {
      provider.icon = fs.readFileSync(iconPath, "utf-8").trim();
    }

    const modelsDir = path.join(providersDir, dir, "models");
    const models: Record<string, unknown>[] = [];

    if (fs.existsSync(modelsDir)) {
      const modelFiles = fs
        .readdirSync(modelsDir)
        .filter((f) => f.endsWith(".json"))
        .sort();

      for (const file of modelFiles) {
        const model = JSON.parse(
          fs.readFileSync(path.join(modelsDir, file), "utf-8"),
        );
        delete model._generated;
        delete model.provider;
        models.push(model);
      }
    }

    providers.push({ id: dir, provider, models });
  }

  // ── Cross-provider inheritance ──

  const INHERIT_FIELDS = [
    "description", "tagline", "context_window", "max_output_tokens",
    "max_input_tokens", "knowledge_cutoff", "training_data_cutoff",
    "license", "parameters", "active_parameters", "architecture",
    "open_weight", "modalities",
  ];

  const directModels = new Map<string, Map<string, Record<string, unknown>>>();
  for (const { provider, models } of providers) {
    if (provider.type !== "direct") continue;
    const byName = new Map<string, Record<string, unknown>>();
    for (const m of models) {
      const mid = (m.id as string).toLowerCase();
      const mname = (m.name as string).toLowerCase();
      byName.set(mid, m);
      if (mid !== mname) byName.set(mname, m);
    }
    directModels.set(provider.id as string, byName);
  }

  const normalizeForMatch = (id: string): string =>
    id.toLowerCase().replace(/^[^/]*\//, "").replace(/@.*$/, "").replace(/[-_]/g, "");

  let inherited = 0;
  for (const { provider, models } of providers) {
    if (provider.type === "direct") continue;
    for (const m of models) {
      const createdBy = m.created_by as string | undefined;
      if (!createdBy) continue;
      const lookup = directModels.get(createdBy);
      if (!lookup) continue;

      const rawId = (m.id as string).toLowerCase();
      const bareId = rawId.replace(/^[^/]*\//, "").replace(/@.*$/, "");
      const normalized = normalizeForMatch(rawId);

      const source =
        lookup.get(bareId) ??
        [...lookup.values()].find(
          (s) => normalizeForMatch(s.id as string) === normalized,
        );
      if (!source) continue;

      let didInherit = false;
      for (const field of INHERIT_FIELDS) {
        if (m[field] == null && source[field] != null) {
          m[field] = source[field];
          didInherit = true;
        }
      }
      if (source.capabilities) {
        const srcCaps = source.capabilities as Record<string, unknown>;
        const mCaps = (m.capabilities ?? {}) as Record<string, unknown>;
        for (const [k, v] of Object.entries(srcCaps)) {
          if (mCaps[k] == null) mCaps[k] = v;
        }
        m.capabilities = mCaps;
      }
      if (didInherit) inherited++;
    }
  }
  if (inherited > 0) {
    console.log(`  inherited fields for ${inherited} aggregator/cloud models`);
  }

  // ── Auto-infer capabilities ──

  for (const { models } of providers) {
    for (const m of models) {
      if (!m.capabilities) continue;
      const caps = m.capabilities as Record<string, unknown>;
      if (m.license && m.license !== "proprietary" && caps.fine_tuning == null) {
        caps.fine_tuning = true;
      }
      if (caps.structured_output && !caps.json_mode) {
        caps.json_mode = true;
      }
      if (
        Array.isArray(m.endpoints) &&
        (m.endpoints as string[]).includes("batch") &&
        caps.batch == null
      ) {
        caps.batch = true;
      }
    }
  }

  // ── Write output ──

  const allData = providers.map(({ provider, models }) => ({ ...provider, models }));

  const lines = [
    ...HEADER,
    "import type { ProviderWithModels, Model } from './types';",
    "",
    `export const providers: ProviderWithModels[] = ${JSON.stringify(allData, null, 2)};`,
    "",
    ...ALL_MODELS_SNIPPET,
  ];

  fs.writeFileSync(DATA_OUTPUT, lines.join("\n"), "utf-8");

  const totalModels = providers.reduce((sum, p) => sum + p.models.length, 0);
  console.log(
    `Generated data-${region}.ts: ${providers.length} providers, ${totalModels} models`,
  );
}

generateRegion(region);

console.log("Done.");
